Exam.EntityFramework/Exam.EntityFramework.MVC/Models/ShipperView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Exam.EntityFramework.MVC.Models
{
    public class ShipperView
    {
        public int Id { get; set; }
        [Required]
        [StringLength(40)]
        [Display(Name = "Nombre *")]
        public string Name { get; set; }
    }
}

Exam.EntityFramework/Exam.EntityFramework.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exam.EntityFramework.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Exam.EntityFramework/Exam.EntityFramework.MVC/Controllers/ShipperController.cs
using Exam.EntityFramework.Entities;
using Exam.EntityFramework.Logic;
using Exam.EntityFramework.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exam.EntityFramework.MVC.Controllers
{
    public class ShipperController : Controller
    {
        ILogic<Shippers> shipperLogic = new ShippersLogic();

        // GET: Shipper
        public ActionResult Index()
        {
            List<Shippers> shippers = shipperLogic.GetAll();
            List<ShipperView> shippersViews = shippers.Select(s => new ShipperView
            {
                Id = s.ShipperID,
                Name = s.CompanyName
            }).ToList();
            return View(shippersViews);
        }

        public ActionResult InsertUpdate(int id = 0)
        {
            ShipperView shipperView = null;
            if (id > 0)
            {
                Shippers shipperEntity = shipperLogic.Get(id);
                shipperView = new ShipperView();
                shipperView.Id = shipperEntity.ShipperID;
                shipperView.Name = shipperEntity.CompanyName;
            }
            return View(shipperView);
        }

        [HttpPost]
        public ActionResult InsertUpdate(ShipperView shipperView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (shipperView.Id == 0)
                    {
                        Shippers shipperEntity = new Shippers
                        {
                            CompanyName = shipperView.Name
                        };
                        shipperLogic.Add(shipperEntity);
                    }
                    else
                    {
                        Shippers shipperEntity = shipperLogic.Get(shipperView.Id);
                        shipperEntity.CompanyName = shipperView.Name;
                        shipperLogic.Update(shipperEntity);
                    }
                    return RedirectToAction("Index");
                }

                return View(shipperView);
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }

        public JsonResult delete(int id = 0)
        {
            bool ok = false;
            string message = "";

            if (id == 0)
            {
                message = "Debe seleccionar el transporte que desea eliminar";
            }
            else
            {
                try
                {
                    shipperLogic.Delete(id);
                    ok = true;
                    message = "El transporte se ha eliminado correctamente";
                }
                catch (System.FormatException e)
                {
                    message = "\nNo se pudo eliminar el transporte. \nMotivo: seguro ingreso una letra o no ingreso nada";
                }
                catch (System.ArgumentNullException)
                {
                    message = "\nNo se pudo eliminar el transporte. \nMotivo: no se encontró ningún transporte con el ID ingresado";
                }
                catch (System.Data.Entity.Infrastructure.DbUpdateException e)
                {
                    message = "\nNo se pudo eliminar el transporte. \nMotivo: el transporte que desea eliminar está siendo utilizado como referencia.";
                }
            }

            return Json(new { ok = ok, message = message }, JsonRequestBehavior.AllowGet);
        }
    }
}

Exam.EntityFramework/Exam.EntityFramework.MVC/Controllers/SweetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SweetAlert.Controllers
{
    public class SweetController : Controller
    {
        // GET: Sweet
        public ActionResult Alert()
        {
            return View();
        }
    }
}

Exam.EntityFramework/Exam.EntityFramework.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Exam.EntityFramework/Exam.EntityFramework.MVC/Views/Home/CharacterRickMorty.cshtml
@{
    ViewBag.Title = "Personajes de Rick & Morty";
}

<div class="row">
    <div class="col-md-12">
        <h2>@ViewBag.Title.</h2>
    </div>
    <div class="col-md-12">
        <div id="characters-api" class="row">
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(function () {

            $.get("https://localhost:44337/api/rickmorty").done(function (data) {

                data.map(function (currentValue) {

                    document.getElementById('characters-api').innerHTML +=
                        `<div class="col-md-3" style="margin: 30px; border-radius: 10px; background: #337ab7; color: white;">
                            <div class="card" style="width: 18rem;">
                                <img src="${currentValue.Image}" class="card-img-top" alt="" style="border-top-right-radius: 10px; border-bottom-right-radius: 10px;">
                                <div class="card-body">
                                    <h5 class="card-title" style="font-weight: bold;">${currentValue.Name}</h5>
                                </div>
                            </div>
                        </div>`;
                });

            }).fail(function (err) {
                swal(
                    '¡Error!',
                    "No se pudo cargar la lista de personajes de Rick & Morty",
                    'error'
                );
            });

        });
    </script>
}

Exam.EntityFramework/Exam.EntityFramework.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Exam.EntityFramework/Exam.EntityFramework.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Exam.EntityFramework/Exam.EntityFramework.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/fontawesome")
    <link href="~/Content/sweetalert/sweet-alert.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Entity Framework MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Transportes", "Index", "Shipper")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/sweetalert.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Exam.EntityFramework/Exam.EntityFramework.MVC/Views/Shipper/InsertUpdate.cshtml
@model Exam.EntityFramework.MVC.Models.ShipperView

@if (Model == null)
{

    ViewBag.Title = "Insertar Transportes";
}
else
{
    ViewBag.Title = "Editar Transportes";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("InsertUpdate", "Shipper", FormMethod.Post))
{
    <div class="row">

        <div class="col-md-12">
            @Html.LabelFor(d => d.Name)
            @Html.TextBoxFor(d => d.Name, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Name, null, new { @class = "text-danger" })
        </div>
        <div class="col-md-12" style="margin-top: 15px;">
            <input class="btn btn-primary" value="Guardar" type="submit" />
        </div>
    </div>
}

Exam.EntityFramework/Exam.EntityFramework.MVC/Views/Shipper/index.cshtml
@model List<Exam.EntityFramework.MVC.Models.ShipperView>

@{
    ViewBag.Title = "Transportes";
}

<div class="row">
    <div class="col-md-2">
        <h2>@ViewBag.Title.</h2>
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("InsertUpdate", "Shipper")" class="btn btn-primary" style="margin-top: 16px;" title="Agregar Transporte"><i class="fa fa-plus" aria-hidden="true"></i></a>
    </div>
</div>

<table class="table table-responsive table-striped">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nombre</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var shipper in Model)
        {
            <tr>
                <td scope="row">@shipper.Id</td>
                <td scope="row">@shipper.Name</td>
                <td scope="row">
                    <a href="@Url.Action("InsertUpdate", "Shipper", new { id = shipper.Id })" class="btn btn-success" title="Editar Transporte"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    <button data-id="@shipper.Id" type="button" class="btn btn-danger btn-delete" title="Eliminar Transporte"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{
    <script>
        $(function () {
            $('.btn-delete').click(function () {
                const id = $(this).data("id");
                swal({
                    title: 'Confirmar',
                    text: "¿Estás seguro que desea el eliminar el transporte?",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: '¡Si, eliminar!'
                }, function (result) {
                    if (result) {

                        const url = "@Url.Action("Delete", "Shipper")";
                        const data = {
                            id: id
                        };

                        $.post(url, data).done(function (data) {
                            location.reload();
                        }).fail(function (err) {
                            swal(
                                '¡Error!',
                                err.responseText,
                                'error'
                            );
                        });
                    }
                })
            });
        });
    </script>
}

Exam.EntityFramework/Exam.EntityFramework.MVC/Views/Sweet/Alert.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="Social Buttons for Bootstrap" />
    <meta property="og:description" content="A beautiful replacement for JavaScript's 'alert' for Bootstrap" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://lipis.github.io/bootstrap-sweetalert/" />
    <meta property="og:image" content="http://lipis.github.io/bootstrap-social/assets/bootstrap-sweetalert.png" />
    <title>SweetAlert for Bootstrap</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-2.1.1.js"></script>
    <link href="https://lipis.github.io/bootstrap-sweetalert/assets/docs.css" rel="stylesheet">
    <!-- Debug -->
    <!-- This is what you need -->
    <script src="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.js"></script>
    <link rel="stylesheet" href="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.css">
    <!--.......................-->
</head>
<body>
    <div class="jumbotron">
        <h1>SweetAlert for Bootstrap</h1>
        <p>A beautiful replacement for JavaScript's "alert"</p>
        <p class="small">
            This is just a clone for Bootstrap of the original
            <a href="http://tristanedwards.me/sweetalert" target="_blank" onclick="_gaq.push(['_trackEvent', 'exit', 'header', 'Original']);">SweetAlert</a>.
        </p>
        <p>
            <a class="btn btn-outline btn-lg" href="https://github.com/lipis/sweetalert" onclick="_gaq.push(['_trackEvent', 'exit', 'main', 'GitHub']);">
                <span class="fa fa-github"></span>
                View on GitHub
            </a>
        </p>
        <ul class="jumbotron-links">
            <li><a href="http://lipis.github.io/bootstrap-social" onclick="_gaq.push(['_trackEvent', 'exit', 'header', 'bootstrap-social']);"><i class="fa fa-group"></i> bootstrap-social</a></li>
            <li><a href="http://lipis.github.io/flag-icon-css" onclick="_gaq.push(['_trackEvent', 'exit', 'header', 'flag-icon-css']);"><i class="fa fa-flag"></i> flag-icon-css</a></li>
        </ul>
        <iframe src="http://ghbtns.com/github-btn.html?user=lipis&amp;repo=bootstrap-sweetalert&amp;type=watch&amp;count=true" class="social-share"></iframe>
        <a href="https://twitter.com/share" class="social-share twitter-share-button" data-url="http://lipis.github.io/bootstrap-sweetalert/" data-text="SweetAlert for Bootstrap! A beautiful replacement for JavaScript's 'alert'." data-via="lipis" data-hashtags="bootstrap">Tweet</a>
    </div>
    <div class="container">
        <h1>Try any of those!</h1>
        <div class="examples">
            <button class="btn btn-lg btn-primary sweet-10">Primary</button>
            <button class="btn btn-lg btn-info sweet-11">Info</button>
            <button class="btn btn-lg btn-success sweet-12">Success</button>
            <button class="btn btn-lg btn-warning sweet-13">Warning</button>
            <button class="btn btn-lg btn-danger sweet-14">Danger</button>
        </div>

        <h2>Install via Bower</h2>
        <pre class="text-center lead">$ bower install bootstrap-sweetalert</pre>
        <p class="text-muted text-center lead">
            Continue playing with the examples or check how to use it on
            <a href="https://github.com/lipis/bootstrap-sweetalert#sweetalert-for-bootstrap">GitHub</a>.
        </p>
        <h2>Original Examples</h2>
        <h4>Basic example</h4>
        <div class="row">
            <div class="col-sm-2 text-center">
                <p><button class="btn btn-primary sweet-1" onclick="_gaq.push(['_trackEvent', 'example', 'try', 'sweet-1']);">Try It</button></p>
            </div>
            <div class="col-sm-10">
                <pre class="code">swal("Here's a message!")</pre>
            </div>
        </div>
        <h4>A title with a text under</h4>
        <div class="row">
            <div class="col-sm-2 text-center">
                <p><button class="btn btn-primary sweet-2" onclick="_gaq.push(['_trackEvent', 'example', 'try', 'sweet-2']);">Try It</button></p>
            </div>
            <div class="col-sm-10">
                <pre>swal("Here's a message!", "It's pretty, isn't it?")</pre>
            </div>
        </div>
        <h4>A success message!</h4>
        <div class="row">
            <div class="col-sm-2 text-center">
                <p><button class="btn btn-primary sweet-3" onclick="_gaq.push(['_trackEvent', 'example', 'try', 'sweet-3']);">Try It</button></p>
            </div>
            <div class="col-sm-10">
                <pre>swal("Good job!", "You clicked the button!", "success")</pre>
            </div>
        </div>
        <h4>A warning message, with a function attached to the "Confirm" button...</h4>
        <div class="row">
            <div class="col-sm-2 text-center">
                <p><button class="btn btn-primary sweet-4" onclick="_gaq.push(['_trackEvent', 'example', 'try', 'sweet-4']);">Try It</button></p>
            </div>
            <div class="col-sm-10">
                <pre>
swal({
  title: "Are you sure?",
  text: "Your will not be able to recover this imaginary file!",
  type: "warning",
  showCancelButton: true,
  confirmButtonClass: "btn-danger",
  confirmButtonText: "Yes, delete it!",
  closeOnConfirm: false
},
function(){
  swal("Deleted!", "Your imaginary file has been deleted.", "success");
});</pre>
            </div>
        </div>
        <h4>...and by passing a parameter, you can execute something else for "Cancel".</h4>
        <div class="row">
            <div class="col-sm-2 text-center">
                <p><button class="btn btn-primary sweet-5" onclick="_gaq.push(['_trackEvent', 'example', 'try', 'sweet-5']);">Try It</button></p>
            </div>
            <div class="col-sm-10">
                <pre>
swal({
  title: "Are you sure?",
  text: "You will not be able to recover this imaginary file!",
  type: "warning",
  showCancelButton: true,
  confirmButtonClass: "btn-danger",
  confirmButtonText: "Yes, delete it!",
  cancelButtonText: "No, cancel plx!",
  closeOnConfirm: false,
  closeOnCancel: false
},
function(isConfirm) {
  if (isConfirm) {
    swal("Deleted!", "Your imaginary file has been deleted.", "success");
  } else {
    swal("Cancelled", "Your imaginary file is safe :)", "error");
  }
});</pre>
            </div>
        </div>
        <h4>A message with a custom icon</h4>
        <div class="row">
            <div class="col-sm-2 text-center">
                <p><button class="btn btn-primary sweet-6" onclick="_gaq.push(['_trackEvent', 'exit', 'footer', 'Lipis']);">Try It</button></p>
            </div>
            <div class="col-sm-10">
                <pre>
swal({
  title: "Sweet!",
  text: "Here's a custom image.",
  imageUrl: 'thumbs-up.jpg'
});</pre>
            </div>
        </div>
    </div>
    <footer>
        <ul class="links">
            <li><a href="http://lip.is" onclick="_gaq.push(['_trackEvent', 'exit', 'footer', 'Lipis']);">Lipis</a></li>
            <li><a href="http://github.com/lipis" onclick="_gaq.push(['_trackEvent', 'exit', 'footer', 'GitHub']);"><i class="fa fa-github"></i> GitHub</a></li>
            <li><a href="http://twitter.com/lipis" onclick="_gaq.push(['_trackEvent', 'exit', 'footer', 'Twitter']);"><i class="fa fa-twitter"></i> Twitter</a></li>
            <li><a href="http://google.com/+PanayiotisLipiridis" onclick="_gaq.push(['_trackEvent', 'exit', 'footer', 'Google+']);"><i class="fa fa-google-plus"></i> Google+</a></li>
            <li><a href="http://opensource.org/licenses/MIT" onclick="_gaq.push(['_trackEvent', 'exit', 'footer', 'MIT']);"><i class="fa fa-building"></i> MIT License</a></li>
        </ul>
    </footer>
    <script>
      document.querySelector('.sweet-1').onclick = function(){
        swal("Here's a message!");
      };

      document.querySelector('.sweet-2').onclick = function(){
        swal("Here's a message!", "It's pretty, isn't it?")
      };

      document.querySelector('.sweet-3').onclick = function(){
        swal("Good job!", "You clicked the button!", "success");
      };

      document.querySelector('.sweet-4').onclick = function(){
        swal({
          title: "Are you sure?",
          text: "You will not be able to recover this imaginary file!",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: 'btn-danger',
          confirmButtonText: 'Yes, delete it!',
          closeOnConfirm: false,
          //closeOnCancel: false
        },
        function(){
          swal("Deleted!", "Your imaginary file has been deleted!", "success");
        });
      };

      document.querySelector('.sweet-5').onclick = function(){
        swal({
          title: "Are you sure?",
          text: "You will not be able to recover this imaginary file!",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: 'btn-danger',
          confirmButtonText: 'Yes, delete it!',
          cancelButtonText: "No, cancel plx!",
          closeOnConfirm: false,
          closeOnCancel: false
        },
        function(isConfirm){
          window.console.log('fuck', isConfirm);
          if (isConfirm){
            swal("Deleted!", "Your imaginary file has been deleted!", "success");
          } else {
            swal("Cancelled", "Your imaginary file is safe :)", "error");
          }
        });
      };

      document.querySelector('.sweet-6').onclick = function(){
        swal({
          title: "Sweet!",
          text: "Here's a custom image.",
          imageUrl: 'assets/thumbs-up.jpg'
        });
      };

      document.querySelector('.sweet-10').onclick = function(){
        swal({
          title: "Are you sure?",
          text: "You will not be able to recover this imaginary file!",
          type: "info",
          showCancelButton: true,
          confirmButtonClass: 'btn-primary',
          confirmButtonText: 'Primary!'
        });
      };

      document.querySelector('.sweet-11').onclick = function(){
        swal({
          title: "Are you sure?",
          text: "You will not be able to recover this imaginary file!",
          type: "info",
          showCancelButton: true,
          confirmButtonClass: 'btn-info',
          confirmButtonText: 'Info!'
        });
      };

      document.querySelector('.sweet-12').onclick = function(){
        swal({
          title: "Are you sure?",
          text: "You will not be able to recover this imaginary file!",
          type: "success",
          showCancelButton: true,
          confirmButtonClass: 'btn-success',
          confirmButtonText: 'Success!'
        });
      };

      document.querySelector('.sweet-13').onclick = function(){
        swal({
          title: "Are you sure?",
          text: "You will not be able to recover this imaginary file!",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: 'btn-warning',
          confirmButtonText: 'Warning!'
        });
      };

      document.querySelector('.sweet-14').onclick = function(){
        swal({
          title: "Are you sure?",
          text: "You will not be able to recover this imaginary file!",
          type: "error",
          showCancelButton: true,
          confirmButtonClass: 'btn-danger',
          confirmButtonText: 'Danger!'
        });
      };
    </script>
    <script>
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
    </script>
</body>
</html>